#!/bin/bash
# WARNING: work in progress
# This script can be run by executing the following:
#   curl -sL https://raw.githubusercontent.com/RJW42/dotfiles/refs/heads/master/installers/install-dotfiles | bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

cd $HOME
mkdir .dotfiles
git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME init -b master
git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME remote add origin git@github.com:RJW42/dotfiles.git
git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME fetch
git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME reset --hard origin/master

cd .config/nvim
git init -b master
git remote add origin git@github.com:RJW42/nvim.git
git reset --hard origin master
cd $HOME
