#!/bin/bash
# WARNING: work in progress
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

cd $HOME
mkdir -p .scratch
cd .scratch
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
cd $HOME
rm -rf .scratch
